Add a FAQ section based on information that is currently locked on our Discord
KyoriPowered/adventure-docs pull request #110
Opened 2023-02-16 00:53 UTC by zml2008

Closes GH-105

2023-02-16 04:22 UTC, kashike requested changes

2023-02-16 04:22 UTC, kashike commented on source/faq.md
> +There are no working, recommended or supported ways of using both MiniMessage and legacy colour codes and there never will be. Even simple find-and-replace style techniques do not work and will fail
```suggestion
There are no working, recommended, or supported ways of using both MiniMessage and legacy colour codes and there never will be. Even simple find-and-replace style techniques do not work and will fail to take into account the quirks of style resetting in legacy formatting.
```

2023-02-19 18:32 UTC, NoahvdAa commented on source/faq.md
> +In vanilla Minecraft, some places were components are rendered have parent styles. For example, lore text has a parent style that makes all text italic. This means that you will need to set italic to
```suggestion
In vanilla Minecraft, some places where components are rendered have parent styles. For example, lore text has a parent style that makes all text italic. This means that you will need to set italic to false if you do not want any component you are storing in lore to be italic. The {java}`Component.decorationIfAbsent()` method can apply this to existing components without overriding any formatting specifically set by users.
```

2023-02-22 02:49 UTC, kashike approved these changes

2023-02-22 03:02 UTC, merged