minimessage-text: added docs for line break (<br>)
KyoriPowered/adventure-docs pull request #61
Opened 2022-02-20 11:37 UTC by JOO200

This is the docs PR for https://github.com/KyoriPowered/adventure/pull/687

2022-02-20 15:31 UTC, KingOfSquares requested changes

2022-02-20 15:31 UTC, KingOfSquares commented on source/minimessage/format.rst
> +   :mm:`<font:key>`
Wrong tag

2022-02-20 19:10 UTC, KingOfSquares commented
Looking at

2022-02-21 22:28 UTC, kezz requested changes

2022-02-21 22:28 UTC, kezz commented on source/minimessage/format.rst
> +New Line
```suggestion
Newline
```

2022-02-21 22:28 UTC, kezz commented on source/minimessage/format.rst
> +Allows you to insert a new line
```suggestion
Insert a newline character.
```

2022-02-21 22:28 UTC, kezz commented on source/minimessage/format.rst
> +   :mm:`<br>`
I'd swap this around, make `<newline>` be the default with `<br>` being the alias.

2022-02-21 22:45 UTC, kezz approved these changes

2022-02-21 22:45 UTC, merged